# Generated by Django 3.2.18 on 2023-04-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'people'), ('model', 'Agent')), models.Q(('app_label', 'people'), ('model', 'Candidate')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_ct', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
