version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    volumes:
      - ./pgdatadb:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5438:${POSTGRES_PORT}'
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  redis:
    image: redis:6
    ports: 
        - 6379:${REDIS_PORT}
    command: redis-server
  fe:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend/public:/public'
      - '/frontend/node_modules'
      - '/frontend/src'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    # command: yarn start
    stdin_open: true
    tty: true
volumes:
  pgdatadb:
